import React from 'react';
import IntellijIcon from '../../components/editors/IntellijIcon';
import WebstormIcon from '../../components/editors/WebstormIcon';
import RiderIcon from '../../components/editors/RiderIcon';
import PycharmIcon from '../../components/editors/PyCharmIcon';
import ClionIcon from '../../components/editors/ClionIcon';
import PhpstormIcon from '../../components/editors/PhpStormIcon';
import RubymineIcon from '../../components/editors/RubyMineIcon';
import GoLandIcon from '../../components/editors/GoLandIcon';
import VsCodeIcon from '../../components/editors/VsCodeIcon';
import BracketsIcon from '../../components/editors/BracketsIcon';
import AndroidStudioIcon from '../../components/editors/AndroidStudioIcon';
import SublimeIcon from '../../components/editors/SublimeIcon';

export const editorIconsMap = {
  IntellijIcon: <IntellijIcon width="30px" height="30px" />,
  WebstormIcon: <WebstormIcon width="30px" height="30px" />,
  RiderIcon: <RiderIcon width="30px" height="30px" />,
  PycharmIcon: <PycharmIcon width="30px" height="30px" />,
  ClionIcon: <ClionIcon width="30px" height="30px" />,
  PhpstormIcon: <PhpstormIcon width="30px" height="30px" />,
  RubymineIcon: <RubymineIcon width="30px" height="30px" />,
  GoLandIcon: <GoLandIcon width="30px" height="30px" />,
  VsCodeIcon: <VsCodeIcon width="30px" height="30px" />,
  BracketsIcon: <BracketsIcon width="30px" height="30px" />,
  AndroidStudioIcon: <AndroidStudioIcon width="30px" height="30px" />,
  SublimeIcon: <SublimeIcon width="30px" height="30px" />,
};

export const editorsCst = [
  {
    key: '0-2',
    label: 'Intellij',
    icon: 'IntellijIcon',
    path: '',
    defaultCommand: 'idea',
    settingsFolder: '.idea',
    enabled: true,
    pathWindows: 'C:\\Program Files\\JetBrains\\IntelliJ IDEA\\bin\\idea.bat',
    pathLinux: '/opt/intellij-idea/bin/idea',
    pathMacOs: '/Applications/IntelliJ IDEA.app/Contents/MacOS/idea',
  },
  {
    key: '0-3',
    label: 'Webstorm',
    icon: 'WebstormIcon',
    path: '',
    defaultCommand: 'webstorm',
    settingsFolder: '.idea',
    enabled: true,
    pathWindows: 'C:\\Program Files\\JetBrains\\WebStorm\\bin\\webstorm.bat',
    pathLinux: '/opt/webstorm/bin/webstorm',
    pathMacOs: '/Applications/WebStorm.app/Contents/MacOS/webstorm',
  },
  {
    key: '0-4',
    label: 'Rider',
    icon: 'RiderIcon',
    path: '',
    defaultCommand: 'rider',
    settingsFolder: '.idea',
    enabled: true,
    pathWindows: 'C:\\Program Files\\JetBrains\\Rider\\bin\\rider.bat',
    pathLinux: '/opt/rider/bin/ride',
    pathMacOs: '/Applications/Rider.app/Contents/MacOS/rider',
  },
  {
    key: '0-5',
    label: 'PyCharm',
    icon: 'PycharmIcon',
    path: '',
    defaultCommand: 'pycharm',
    settingsFolder: '.idea',
    enabled: true,
    pathWindows: 'C:\\Program Files\\JetBrains\\PyCharm\\bin\\pycharm.bat',
    pathLinux: '/opt/pycharm/bin/pycharm',
    pathMacOs: '/Applications/PyCharm.app/Contents/MacOS/pycharm',
  },
  {
    key: '0-6',
    label: 'CLion',
    icon: 'ClionIcon',
    path: '',
    defaultCommand: 'clion',
    settingsFolder: '.idea',
    enabled: true,
    pathWindows: 'C:\\Program Files\\JetBrains\\CLion\\bin\\clion.bat',
    pathLinux: '/opt/clion/bin/clion',
    pathMacOs: '/Applications/CLion.app/Contents/MacOS/clion',
  },
  {
    key: '0-7',
    label: 'PhpStorm',
    icon: 'PhpstormIcon',
    path: '',
    defaultCommand: 'phpstorm',
    settingsFolder: '.idea',
    enabled: true,
    pathWindows: 'C:\\Program Files\\JetBrains\\PhpStorm\\bin\\phpstorm.bat',
    pathLinux: '/opt/phpstorm/bin/phpstorm',
    pathMacOs: '/Applications/PhpStorm.app/Contents/MacOS/phpstorm',
  },
  {
    key: '0-8',
    label: 'RubyMine',
    icon: 'RubymineIcon',
    path: '',
    defaultCommand: 'rubymine',
    settingsFolder: '.idea',
    enabled: true,
    pathWindows: 'C:\\Program Files\\JetBrains\\RubyMine\\bin\\rubymine.bat',
    pathLinux: '/opt/rubymine/bin/rubymine',
    pathMacOs: '/Applications/RubyMine.app/Contents/MacOS/rubymine',
  },
  {
    key: '0-9',
    label: 'GoLand',
    icon: 'GoLandIcon',
    path: '',
    defaultCommand: 'goland',
    settingsFolder: '.idea',
    enabled: true,
    pathWindows: 'C:\\Program Files\\JetBrains\\GoLand\\bin\\goland.bat',
    pathLinux: '/opt/goland/bin/goland',
    pathMacOs: '/Applications/GoLand.app/Contents/MacOS/goland',
  },
  {
    key: '0-10',
    label: 'Visual Studio',
    icon: 'VsCodeIcon',
    path: '',
    defaultCommand: 'code',
    settingsFolder: '.vscode',
    enabled: true,
    pathWindows: 'C:\\Program Files\\Microsoft VS Code\\bin\\code.cmd',
    pathLinux: '/usr/share/code/code',
    pathMacOs:
      '/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code',
  },
  {
    key: '0-12',
    label: 'Brackets',
    icon: 'BracketsIcon',
    path: '',
    defaultCommand: 'brackets',
    settingsFile: '.brackets.json',
    enabled: true,
    pathWindows: 'C:\\Program Files (x86)\\Brackets\\brackets.exe',
    pathLinux: '/opt/brackets/brackets',
    pathMacOs: '/Applications/Brackets.app/Contents/MacOS/Brackets',
  },
  {
    key: '0-13',
    label: 'Android Studio',
    icon: 'AndroidStudioIcon',
    path: '',
    defaultCommand: 'studio',
    settingsFolder: '.idea',
    enabled: true,
    pathWindows: 'C:\\Program Files\\Android\\Android Studio\\bin\\studio.bat',
    pathLinux: '/opt/android-studio/bin/studio.sh',
    pathMacOs: '/Applications/Android Studio.app/Contents/MacOS/studio',
  },
  {
    key: '0-14',
    label: 'Sublime Text',
    icon: 'SublimeIcon',
    path: '',
    defaultCommand: 'subl',
    settingsFolder: '.sublime-project',
    enabled: true,
    pathWindows: 'C:\\Program Files\\Sublime Text\\subl.exe',
    pathLinux: '/opt/sublime_text/subl',
    pathMacOs: '/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl',
  },
];
