name: Build WorktreeWise

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: List files in src/renderer (for debugging)
        run: ls -alR src/renderer

      - name: Clean build directory
        run: npm run clean  # Clean up old build files

      - name: Build application
        run: npm run build

      - name: Package application
        env:
          CSC_LINK: ${{ secrets.CSC_LINK || ''  }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD || ''  }}
        run: npm run package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WorktreeWise-${{ matrix.os }}
          path: release/build/*.zip
